# -*- coding: utf-8 -*-
"""dataAnalysis_hotel_cancellation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKqCu2v0QM4hwPZXeQ_mP4BDPWH7nGLM

#importing labriries
"""

import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""**Loading the dataset**"""

df = pd.read_csv("hotel_bookings 2.csv")

"""**Exploratory Data Analysis** **and Data Cleaning**"""

df.head()

df.tail()

df.columns

df.shape

df.info()   #see datatype and non-null value

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], errors='coerce')

df.info()

df.describe(include = 'object') #object col ka summary mil jae ga include s

# obj col m ktne categories h
for col in df.describe(include = 'object').columns:
  print(col)
  print(df[col].unique())

df.isnull().sum() #col name and missing values



"""#agent ko remove kreg bcz no use , company k bht zyada missing value h to handle krna mushkl h so remove,
#country cl mese 1 lac mese srf 488 misssing to drp kreg hata **deng**
"""

df.drop(['company','agent'], axis = 1, inplace = True)
df.dropna(inplace = True)

df.isnull().sum()

df.describe()

df['adr'].plot(kind = 'box')

"""**data analysis and visualizations**"""

# Calculate percentages correctly
cancelled_perc = df['is_canceled'].value_counts(normalize=True)
print("Percentages:")
print(cancelled_perc)

# Get counts for the bar chart
counts = df['is_canceled'].value_counts().sort_index()  # Sort to ensure 0,1 order

# Create the plot
plt.figure(figsize=(6, 5))
plt.title('Reservation Status Count')

# Create bars with correct order
categories = ['Not Canceled (0)', 'Canceled (1)']
plt.bar(categories, counts, edgecolor='k', width=0.6,
        color=['green', 'red'], alpha=0.7)

# Add value labels on top of bars
for i, count in enumerate(counts):
    plt.text(i, count + 0.01 * counts.max(),
             f'{count:,}\n({cancelled_perc[i]:.1%})',
             ha='center', va='bottom', fontweight='bold')

# Add grid for better readability
plt.grid(axis='y', alpha=0.3, linestyle='--')

plt.ylabel('Number of Reservations')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Print summary statistics
print(f"\nSummary:")
print(f"Total reservations: {len(df):,}")
print(f"Canceled: {counts[1]:,} ({cancelled_perc[1]:.2%})")
print(f"Not Canceled: {counts[0]:,} ({cancelled_perc[0]:.2%})")

"""**depending on hotels find**"""

plt.figure(figsize=(10, 6))

# Create countplot with better color palette
ax = sns.countplot(x='hotel', hue='is_canceled', data=df,
                   palette=['#2E86AB', '#A23B72'],  # Custom colors
                   edgecolor='black', linewidth=1.5,
                   saturation=0.85)

# Add title with more context
plt.title('Hotel Booking Cancellations by Hotel Type\n(With Percentage Breakdown)',
          fontsize=16, fontweight='bold', pad=20)

# Calculate and add percentage labels on each bar
for p in ax.patches:
    height = p.get_height()
    if height > 0:  # Only label bars with data
        # Calculate percentage within each hotel group
        total_in_hotel = sum([patch.get_height() for patch in ax.patches
                             if patch.get_x() == p.get_x()])
        percentage = f'{(height/total_in_hotel)*100:.1f}%'

        # Add text with count and percentage
        ax.text(p.get_x() + p.get_width()/2.,  # x position
                height + 0.01 * max([patch.get_height() for patch in ax.patches]),  # y position
                f'{int(height):,}\n({percentage})',  # text
                ha='center', va='bottom',
                fontsize=10, fontweight='bold',
                color='black')

# Customize legend
legend_labels = ['Not Canceled (0)', 'Canceled (1)']
handles, _ = ax.get_legend_handles_labels()
ax.legend(handles, legend_labels, title='Reservation Status',
          title_fontsize=12, fontsize=11,
          frameon=True, fancybox=True, shadow=True,
          facecolor='white', edgecolor='gray')

# Customize axis labels
plt.xlabel('Hotel Type', fontsize=14, fontweight='bold', labelpad=10)
plt.ylabel('Number of reservation', fontsize=14, fontweight='bold', labelpad=10)

# Add grid for better readability
ax.yaxis.grid(True, linestyle='--', alpha=0.3, color='gray')
ax.set_axisbelow(True)  # Grid behind bars

# Rotate x-axis labels if needed
plt.xticks(fontsize=12, rotation=0)

# Add total count annotation
for i, hotel in enumerate(df['hotel'].unique()):
    hotel_data = df[df['hotel'] == hotel]
    total_bookings = len(hotel_data)
    canceled_percentage = (hotel_data['is_canceled'].mean() * 100)

    ax.text(i, -0.15 * max([patch.get_height() for patch in ax.patches]),
            f'Total: {total_bookings:,}\nCancel Rate: {canceled_percentage:.1f}%',
            ha='center', va='top', fontsize=11, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='lightyellow',
                     edgecolor='gold', alpha=0.9))

# Adjust y-axis limit for better spacing
max_height = max([p.get_height() for p in ax.patches])
ax.set_ylim(0, max_height * 1.15)

# Add a horizontal line for reference
mean_cancel_rate = df['is_canceled'].mean() * 100
ax.axhline(y=max_height * 1.1, color='gray', linestyle=':', alpha=0.5, linewidth=1)
ax.text(len(df['hotel'].unique()) - 0.5, max_height * 1.12,
        f'Overall Cancel Rate: {mean_cancel_rate:.1f}%',
        fontsize=11, ha='right', style='italic', color='darkred')

# Tight layout
plt.tight_layout()

# Show the plot
plt.show()

# Additional statistical summary
print("="*60)
print("DETAILED STATISTICAL SUMMARY:")
print("="*60)

for hotel in df['hotel'].unique():
    hotel_data = df[df['hotel'] == hotel]
    total = len(hotel_data)
    canceled = hotel_data['is_canceled'].sum()
    not_canceled = total - canceled

    print(f"\n{hotel.upper()}:")
    print(f"  Total Bookings: {total:,}")
    print(f"  Canceled: {canceled:,} ({canceled/total*100:.1f}%)")
    print(f"  Not Canceled: {not_canceled:,} ({not_canceled/total*100:.1f}%)")

# Calculate and display the difference between hotels
if len(df['hotel'].unique()) == 2:
    hotel1, hotel2 = df['hotel'].unique()
    rate1 = df[df['hotel'] == hotel1]['is_canceled'].mean() * 100
    rate2 = df[df['hotel'] == hotel2]['is_canceled'].mean() * 100

    print(f"\n{'='*60}")
    print(f"CANCELLATION RATE COMPARISON:")
    print(f"{hotel1}: {rate1:.1f}%")
    print(f"{hotel2}: {rate2:.1f}%")
    print(f"Difference: {abs(rate1 - rate2):.1f} percentage points")
    print(f"{hotel1} has {abs(rate1 - rate2)/rate2*100:.1f}% {'higher' if rate1 > rate2 else 'lower'} cancellation rate than {hotel2}")

resort_hotel = df[df['hotel'] == 'Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize = True)

city_hotel = df[df['hotel'] == 'City Hotel']
city_hotel['is_canceled'].value_counts(normalize = True)

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize = (20,8))
plt.title('Average Daily Rate in City and Resort Hotel', fontsize = 30)
plt.plot(resort_hotel.index, resort_hotel['adr'], label = 'Resort Hotel')
plt.plot(city_hotel.index, city_hotel['adr'], label = 'City Hotel')
plt.legend(fontsize = 20)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# FIRST: Convert string dates to proper datetime
print("Converting string dates to datetime...")

# Reset index if needed (if date is in index)
resort_hotel = resort_hotel.copy()
city_hotel = city_hotel.copy()

# Convert index from string to datetime
resort_hotel.index = pd.to_datetime(resort_hotel.index, format='%m/%d/%Y')
city_hotel.index = pd.to_datetime(city_hotel.index, format='%m/%d/%Y')

print(f"Resort Hotel dates converted: {resort_hotel.index.dtype}")
print(f"City Hotel dates converted: {city_hotel.index.dtype}")
print(f"\nResort Hotel date range: {resort_hotel.index.min()} to {resort_hotel.index.max()}")
print(f"City Hotel date range: {city_hotel.index.min()} to {city_hotel.index.max()}")

# Sort by date (important for line plots)
resort_hotel = resort_hotel.sort_index()
city_hotel = city_hotel.sort_index()

# NOW create the plot
plt.figure(figsize=(20, 10))

# Plot with proper datetime index
plt.plot(resort_hotel.index, resort_hotel['adr'],
         label='Resort Hotel',
         linewidth=3,
         color='#2E86AB',
         marker='o',
         markersize=6,
         markevery=20)  # Show marker every 20 points

plt.plot(city_hotel.index, city_hotel['adr'],
         label='City Hotel',
         linewidth=3,
         color='#A23B72',
         marker='s',
         markersize=6,
         linestyle='--',
         markevery=20)

# Title with date range
start_date = resort_hotel.index.min().strftime('%b %d, %Y')
end_date = resort_hotel.index.max().strftime('%b %d, %Y')
plt.title(f'Average Daily Rate Comparison\n{start_date} to {end_date}\nResort Hotel vs City Hotel',
          fontsize=24, fontweight='bold', pad=20)

# Format x-axis dates properly
plt.gca().xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter('%b %Y'))
plt.gca().xaxis.set_major_locator(plt.matplotlib.dates.MonthLocator(interval=3))
plt.xticks(rotation=45, fontsize=12, ha='right')

# Labels
plt.xlabel('Date', fontsize=16, fontweight='bold', labelpad=10)
plt.ylabel('Average Daily Rate ($)', fontsize=16, fontweight='bold', labelpad=10)

# Add legend with statistics
resort_mean = resort_hotel['adr'].mean()
city_mean = city_hotel['adr'].mean()

legend_labels = [
    f'Resort Hotel (Mean: ${resort_mean:.2f})',
    f'City Hotel (Mean: ${city_mean:.2f})'
]
plt.legend(legend_labels, fontsize=14, frameon=True, shadow=True,
           facecolor='white', edgecolor='gray')

# Add grid
plt.grid(True, alpha=0.3, linestyle='--')

# Add horizontal lines for means
plt.axhline(y=resort_mean, color='#2E86AB', linestyle=':', alpha=0.5, linewidth=2)
plt.axhline(y=city_mean, color='#A23B72', linestyle=':', alpha=0.5, linewidth=2)

# Add vertical lines for year boundaries
for year in range(resort_hotel.index.min().year, resort_hotel.index.max().year + 1):
    plt.axvline(x=pd.Timestamp(f'{year}-01-01'), color='gray', linestyle=':',
                alpha=0.3, linewidth=1)
    # Add year labels
    plt.text(pd.Timestamp(f'{year}-03-01'), plt.ylim()[1] * 0.95,
             str(year), fontsize=11, alpha=0.7, ha='center')

# Set y-axis to start from 0
plt.ylim(0, max(resort_hotel['adr'].max(), city_hotel['adr'].max()) * 1.15)

# Add value annotations for key points (min, max, etc.)
resort_max_idx = resort_hotel['adr'].idxmax()
city_max_idx = city_hotel['adr'].idxmax()

plt.annotate(f'Max: ${resort_hotel["adr"].max():.2f}',
             xy=(resort_max_idx, resort_hotel['adr'].max()),
             xytext=(10, 10), textcoords='offset points',
             arrowprops=dict(arrowstyle='->', color='#2E86AB'),
             fontsize=11, fontweight='bold', color='#2E86AB')

plt.annotate(f'Max: ${city_hotel["adr"].max():.2f}',
             xy=(city_max_idx, city_hotel['adr'].max()),
             xytext=(10, -20), textcoords='offset points',
             arrowprops=dict(arrowstyle='->', color='#A23B72'),
             fontsize=11, fontweight='bold', color='#A23B72')

plt.tight_layout()
plt.show()

# Print detailed analysis
print("\n" + "="*70)
print("ANALYSIS REPORT")
print("="*70)

print(f"\nDate Analysis:")
print(f"  Resort Hotel covers: {resort_hotel.index.min().strftime('%Y-%m-%d')} to {resort_hotel.index.max().strftime('%Y-%m-%d')}")
print(f"  City Hotel covers: {city_hotel.index.min().strftime('%Y-%m-%d')} to {city_hotel.index.max().strftime('%Y-%m-%d')}")
print(f"  Total days for Resort: {(resort_hotel.index.max() - resort_hotel.index.min()).days} days")
print(f"  Total days for City: {(city_hotel.index.max() - city_hotel.index.min()).days} days")

print(f"\nPrice Analysis:")
print(f"  Resort Hotel Mean ADR: ${resort_mean:.2f}")
print(f"  City Hotel Mean ADR: ${city_mean:.2f}")
print(f"  Difference: ${abs(resort_mean - city_mean):.2f}")

if resort_mean > city_mean:
    print(f"  Resort is ${resort_mean - city_mean:.2f} MORE expensive ({((resort_mean/city_mean)-1)*100:.1f}% higher)")
else:
    print(f"  Resort is ${city_mean - resort_mean:.2f} LESS expensive ({((city_mean/resort_mean)-1)*100:.1f}% lower)")

print(f"\nVariability Analysis:")
print(f"  Resort Hotel Std Dev: ${resort_hotel['adr'].std():.2f} ({(resort_hotel['adr'].std()/resort_mean)*100:.1f}% of mean)")
print(f"  City Hotel Std Dev: ${city_hotel['adr'].std():.2f} ({(city_hotel['adr'].std()/city_mean)*100:.1f}% of mean)")

print(f"\nPrice Range:")
print(f"  Resort Hotel: ${resort_hotel['adr'].min():.2f} to ${resort_hotel['adr'].max():.2f}")
print(f"  City Hotel: ${city_hotel['adr'].min():.2f} to ${city_hotel['adr'].max():.2f}")

# Calculate and show monthly averages
print(f"\nMonthly Averages:")
resort_monthly = resort_hotel['adr'].resample('M').mean()
city_monthly = city_hotel['adr'].resample('M').mean()

for month in resort_monthly.index.intersection(city_monthly.index):
    month_str = month.strftime('%b %Y')
    print(f"  {month_str}: Resort ${resort_monthly[month]:.2f} | City ${city_monthly[month]:.2f}")

df['month'] = df['reservation_status_date'].dt.month

plt.figure(figsize=(16, 8))
ax = sns.countplot(x='month', hue='is_canceled', data=df, palette=['#2E86AB', '#A23B72'],
                   edgecolor='black', linewidth=1.5)

plt.title('Monthly Booking Analysis: Canceled vs Non-Canceled Reservations',
          fontsize=22, fontweight='bold', pad=20)
plt.xlabel('Month', fontsize=16, fontweight='bold', labelpad=10)
plt.ylabel('Number of Reservations', fontsize=16, fontweight='bold', labelpad=10)

# Customize legend
legend_labels = ['Not Canceled (0)', 'Canceled (1)']
handles, _ = ax.get_legend_handles_labels()
ax.legend(handles, legend_labels, title='Reservation Status',
          title_fontsize=14, fontsize=12,
          frameon=True, fancybox=True, shadow=True,
          facecolor='white', edgecolor='gray')

# Add month names
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
ax.set_xticklabels(month_names, fontsize=13)

# Add percentage labels on top of each bar group
for container in ax.containers:
    for bar in container:
        height = bar.get_height()
        if height > 0:
            # Calculate percentage within each month
            month_idx = bar.get_x() + bar.get_width() / 2
            month = int(month_idx)  # Get month index
            month_data = df[df['month'] == month + 1]  # +1 because months are 1-12
            total_in_month = len(month_data)

            status = 0 if container == ax.containers[0] else 1
            count_in_month = len(month_data[month_data['is_canceled'] == status])
            percentage = (count_in_month / total_in_month) * 100

            ax.text(bar.get_x() + bar.get_width()/2, height + 5,
                    f'{percentage:.1f}%', ha='center', va='bottom',
                    fontsize=10, fontweight='bold')

# Add grid for better readability
plt.grid(axis='y', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 8))

# Group and prepare data
canceled_data = df[df['is_canceled'] == 1]
monthly_adr_sum = canceled_data.groupby('month')['adr'].sum().reset_index()

# Create barplot
sns.barplot(x='month', y='adr', data=monthly_adr_sum,
            palette='viridis', edgecolor='black', linewidth=1.5)

plt.title('Total ADR of Canceled Bookings per Month', fontsize=24, fontweight='bold', pad=20)
plt.xlabel('Month', fontsize=16, fontweight='bold')
plt.ylabel('Total ADR ($)', fontsize=16, fontweight='bold')

# Format y-axis with comma separators
plt.gca().yaxis.set_major_formatter(plt.matplotlib.ticker.StrMethodFormatter('{x:,.0f}'))

# Add value labels on top of bars
for i, value in enumerate(monthly_adr_sum['adr']):
    plt.text(i, value + (monthly_adr_sum['adr'].max() * 0.01),
             f'${value:,.0f}',
             ha='center', va='bottom', fontsize=11, fontweight='bold')

plt.grid(axis='y', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

cancelled_data = df[df['is_canceled'] == 1]
top_10_country = cancelled_data['country'].value_counts()[:10]

plt.figure(figsize=(8, 8))
plt.title('Top 10 Countries with Reservation Canceled', fontsize=14)
plt.pie(top_10_country, autopct='%.2f%%', labels=top_10_country.index)  # Fixed: autopct not autop<t
plt.axis('equal')  # Makes the pie chart circular
plt.show()

df['market_segment'].value_counts()

df['market_segment'].value_counts(normalize = True)

cancelled_data['market_segment'].value_counts(normalize = True)

cancelled_data = df[df['is_canceled'] == 1]
cancelled_df_adr = cancelled_data.groupby('reservation_status_date')[['adr']].mean()
cancelled_df_adr.reset_index(inplace=True)
cancelled_df_adr.sort_values('reservation_status_date', inplace=True)

not_cancelled_data = df[df['is_canceled'] == 0]
not_cancelled_df_adr = not_cancelled_data.groupby('reservation_status_date')[['adr']].mean()
not_cancelled_df_adr.reset_index(inplace=True)
not_cancelled_df_adr.sort_values('reservation_status_date', inplace=True)

# Create figure
plt.figure(figsize=(20, 8))

# Plot both lines
plt.plot(not_cancelled_df_adr['reservation_status_date'],
         not_cancelled_df_adr['adr'],
         label='Not Cancelled',
         linewidth=2,
         color='green',
         alpha=0.8)

plt.plot(cancelled_df_adr['reservation_status_date'],
         cancelled_df_adr['adr'],
         label='Cancelled',
         linewidth=2,
         color='red',
         alpha=0.8,
         linestyle='--')

# Add title and labels
plt.title('Average Daily Rate: Cancelled vs Not Cancelled Bookings',
          fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Reservation Status Date', fontsize=14)
plt.ylabel('Average Daily Rate (ADR)', fontsize=14)

# Add legend
plt.legend(fontsize=12, loc='best')

# Format x-axis dates
plt.gca().xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter('%Y-%m-%d'))
plt.gca().xaxis.set_major_locator(plt.matplotlib.dates.AutoDateLocator())
plt.xticks(rotation=45, fontsize=10)
plt.gcf().autofmt_xdate()

# Add grid
plt.grid(True, alpha=0.3, linestyle='--')

# Set y-axis to start from 0
plt.ylim(0, max(cancelled_df_adr['adr'].max(), not_cancelled_df_adr['adr'].max()) * 1.1)

# Add horizontal lines for mean values
cancelled_mean = cancelled_df_adr['adr'].mean()
not_cancelled_mean = not_cancelled_df_adr['adr'].mean()

plt.axhline(y=cancelled_mean, color='red', linestyle=':', alpha=0.5, linewidth=1.5)
plt.axhline(y=not_cancelled_mean, color='green', linestyle=':', alpha=0.5, linewidth=1.5)

# Add mean value annotations
plt.text(not_cancelled_df_adr['reservation_status_date'].iloc[-1],
         not_cancelled_mean + 2,
         f'Not Cancelled Mean: ${not_cancelled_mean:.2f}',
         color='green', fontsize=11, fontweight='bold')

plt.text(cancelled_df_adr['reservation_status_date'].iloc[-1],
         cancelled_mean - 5,
         f'Cancelled Mean: ${cancelled_mean:.2f}',
         color='red', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

# Print summary statistics
print("="*70)
print("SUMMARY STATISTICS")
print("="*70)
print(f"\nCancelled Bookings:")
print(f"  Date Range: {cancelled_df_adr['reservation_status_date'].min().date()} to {cancelled_df_adr['reservation_status_date'].max().date()}")
print(f"  Number of days: {len(cancelled_df_adr)}")
print(f"  Mean ADR: ${cancelled_df_adr['adr'].mean():.2f}")
print(f"  Max ADR: ${cancelled_df_adr['adr'].max():.2f}")
print(f"  Min ADR: ${cancelled_df_adr['adr'].min():.2f}")

print(f"\nNot Cancelled Bookings:")
print(f"  Date Range: {not_cancelled_df_adr['reservation_status_date'].min().date()} to {not_cancelled_df_adr['reservation_status_date'].max().date()}")
print(f"  Number of days: {len(not_cancelled_df_adr)}")
print(f"  Mean ADR: ${not_cancelled_df_adr['adr'].mean():.2f}")
print(f"  Max ADR: ${not_cancelled_df_adr['adr'].max():.2f}")
print(f"  Min ADR: ${not_cancelled_df_adr['adr'].min():.2f}")

print(f"\nComparison:")
diff = not_cancelled_mean - cancelled_mean
if diff > 0:
    print(f"  Not cancelled bookings are ${abs(diff):.2f} MORE expensive on average")
else:
    print(f"  Not cancelled bookings are ${abs(diff):.2f} LESS expensive on average")